# POST https://jphacks.shuttleapp.rs/judge-captcha HTTP/1.1
# Content-Type: application/json


# [
#     {
#         "image_url": "testurl", 
#         "object_label": "cat",
#         "noise_info": "noiseeeee",
#         "forbidden_label": true
#     }
# ]


GET http://localhost:5000/ HTTP/1.1


# POST https://jphacks.shuttleapp.rs/image_upload HTTP/1.1
# Content-Type: application/json

# {
#     "image_url": "testurl", 
#     "object_label": "cat",
#     "noise_info": "noiseeeee",
#     "forbidden_label": true
# }

# GET https://jphacks.shuttleapp.rs/get-capthcha-images/cat HTTP/1.1

# {
#     "image_url":"https",
#     "object_label":"una",
#     "noise_info":"noised",
#     "forbidden_label":false
# }