# POST https://jphacks.shuttleapp.rs/judge-captcha HTTP/1.1
# Content-Type: application/json


# [
#     {
#         "image_url": "testurl", 
#         "object_label": "cat",
#         "noise_info": "noiseeeee",
#         "forbidden_label": true
#     }
# ]


# GET https://jphacks.shuttleapp.rs/Una HTTP/1.1


# POST https://jphacks.shuttleapp.rs/image_upload HTTP/1.1
# Content-Type: application/json

# {
#     "image_url": "testurl", 
#     "object_label": "cat",
#     "noise_info": "noiseeeee",
#     "forbidden_label": true
# }

# GET https://jphacks.shuttleapp.rs/get-capthcha-images/rabbit HTTP/1.1

# GET http://127.0.0.1:8000/get-capthcha-images/rabbit HTTP/1.1
# {
#     "image_url":"https",
#     "object_label":"una",
#     "noise_info":"noised",
#     "forbidden_label":false
# }

# POST https://vision.googleapis.com/v1/images:annotate?key=
# Content-Type: application/json


# {
#   "requests":[
#     {
#       "image":{
# "source": {
#           "imageUri": "gs://cloud-samples-data/vision/demo-img.jpg"
# }
#       },
#       "features":[
#         {
#           "type":"LABEL_DETECTION",
#           "maxResults":2
#         }
#       ]
#     }
#   ]
# }

# 返ってくるデータ
# {
#   "responses": [
#     {
#       "labelAnnotations": [
#         {
#           "mid": "/m/0199g",
#           "description": "Bicycle",
#           "score": 0.98430496,
#           "topicality": 0.98430496
#         },
#         {
#           "mid": "/m/083wq",
#           "description": "Wheel",
#           "score": 0.976651,
#           "topicality": 0.976651
#         }
#       ]
#     }
#   ]
# }